### ISSUE TITLE
Implementation Data Models

### ISSUE THREAD

**Issue by YinuoLiu0708** [comp423-23s/final-project-final-e3#4]
![image](https://user-images.githubusercontent.com/77820812/226995788-f9cff364-6b84-4c45-b1b9-f8fafb9a6980.jpeg)

**Comment by tianyiniu** [comment]
![image](https://user-images.githubusercontent.com/77805633/228126249-b452057f-5c72-4e05-be45-e601969b00ad.png)

**Comment by tianyiniu** [comment]
> ![image](https://user-images.githubusercontent.com/77805633/228126249-b452057f-5c72-4e05-be45-e601969b00ad.png)

Updated Data Models

**Comment by tianyiniu** [comment]
**Routes** 

GET for a list of Rooms/Equipment:
"/room" & "/equipment"

POST for a new reservation:
"/reserve/room/name=<Room_name>", payload=Reservation

GET for a list of existing Room/Equipment reservations by name:
"/room/room=<Room_name>"

**Comment by tianyiniu** [comment]
Data models and routes compiled on [google doc](https://docs.google.com/document/d/1B3_ho1e1mM3T3gi-_pXeyd3TRWzzcPmS554FrmVw4F8/edit?usp=sharing)
